meta_product_name: "Parmageddon"
meta_title: "Parmageddon | Find a parma that's right for you, rated by you"
meta_description: "Find and rate venues in your local area for the dish Chicken Parmigiana. All ratings are entered by users - that means you!"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account" # required for Twitter Cards
